spring:
  webflux:
    # hidden으로 지정된 웹 메소드(DELETE, PUT, PATCH) 처리 활성화
    hiddenmethod:
      filter:
        enabled: true
  devtools:
    restart:
      # 재시작 유발 배제 경로 지정
      exclude: static/**,public/**
#      # 자동재시작 사용여부
#      enabled: true
#      # classpath 감지 주기 설정(선택사항)
#      # 빌드하는 시간이 오래걸려 재시작 주기를 길게 가져가고 싶다면 아래의 값을 이용해 갱신
#      # poll-interval 값은 항상 quiet-period 보다 커야한다
#      #poll-interval: 2s
#      #quiet-period: 1s
  thymeleaf:
    # 개발환경에서 캐시 기능 비활성화
    cache: false
logging:
  level:
    com:
      gregturnquist: debug
    # web 로깅 그룹 로깅 활성화
    web: debug

# 액추에이터 설정
management:
  endpoint:
    health:
      # 서버 상태 세부정보 표시 설정
      show-details: always
  endpoints:
    web:
      exposure:
        # 모든 액추에이터 엔드포인트를 웹으로 공개
        include: '*'
        # 공개할 엔드포인트를 명시적으로 지정
        #include: auditevents,beans,caches,conditions,configprops,env,flyway,health,heapdump,httptrace,info,logfile,loggers,metrics,mappings,shutdown,threaddump
      # 액추에이터 루트 엔드 포인트 변경
      #base-path: /
      # 액추에이터 상세 경로 변경
      #path-mapping:
      #  loggers: logs

# 애플리케이션 버전 정보 추가
info:
  project:
    name: ${rootProject.name}
    group: ${group}
    version: ${version}
    #springProperty: \${spring-boot.version}
  java:
    version: \${java.version}
  spring:
    boot:
      version: ${ext.springBootVersion}